# Generated by Django 5.1 on 2024-08-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0009_alter_product_category_alter_sale_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='disco',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='procesador',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='ram',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_selling',
            new_name='tamaño_pantalla',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='voltaje',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='discount',
            new_name='descuento',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gama baja', 'Gama baja'), ('Gaming', 'Gaming'), ('Gama media', 'Gama media'), ('Oficina', 'Oficina'), ('Gama alta', 'Gama alta')], max_length=45),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('Gama baja', 'Gama baja'), ('Gaming', 'Gaming'), ('Gama media', 'Gama media'), ('Oficina', 'Oficina'), ('Gama alta', 'Gama alta')], max_length=45),
        ),
    ]
