# Generated by Django 5.1 on 2024-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0010_rename_address_client_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Oficina', 'Oficina'), ('Gaming', 'Gaming'), ('Gama alta', 'Gama alta'), ('Gama media', 'Gama media'), ('Gama baja', 'Gama baja')], max_length=45),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('Oficina', 'Oficina'), ('Gaming', 'Gaming'), ('Gama alta', 'Gama alta'), ('Gama media', 'Gama media'), ('Gama baja', 'Gama baja')], max_length=45),
        ),
    ]
