# Generated by Django 5.1 on 2024-08-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0011_alter_product_category_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gama alta', 'Gama alta'), ('Gama media', 'Gama media'), ('Oficina', 'Oficina'), ('Gama baja', 'Gama baja'), ('Gaming', 'Gaming')], max_length=45),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('Gama alta', 'Gama alta'), ('Gama media', 'Gama media'), ('Oficina', 'Oficina'), ('Gama baja', 'Gama baja'), ('Gaming', 'Gaming')], max_length=45),
        ),
    ]
