# Generated by Django 5.1 on 2024-08-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0014_alter_product_category_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Gama alta', 'Gama alta'), ('Oficina', 'Oficina'), ('Gama baja', 'Gama baja'), ('Gaming', 'Gaming'), ('Gama media', 'Gama media')], max_length=45),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.CharField(choices=[('Gama alta', 'Gama alta'), ('Oficina', 'Oficina'), ('Gama baja', 'Gama baja'), ('Gaming', 'Gaming'), ('Gama media', 'Gama media')], max_length=45),
        ),
    ]
