# Generated by Django 5.1 on 2024-08-15 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0019_alter_product_category_alter_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Oficina', 'Oficina'), ('Gaming', 'Gaming'), ('Gama alta', 'Gama alta'), ('Gama media', 'Gama media'), ('Gama baja', 'Gama baja')], max_length=45),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(upload_to='laptops_images'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.client'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.product'),
        ),
    ]
